### ISSUE TITLE
Movement primitives

### ISSUE THREAD

**Issue by briemla** [AlSzacrel/mindstorms#3]
Implement class to control simple movements:
- full speed
- stop
- slow backwards
- sharp turn left/right (differential forward backward)
- correction left/right (while driving straight on)
- turn left/right
- slow forward

**Comment by murchandamus** [comment]
Es gibt einige Movement Primitives, aber diese sollten noch getestet werden. Idee: Ein Programm, dass alle Movement Primitives der Reihe nach durchführt.
